id: PF0D4399F
initial_creation_type: ocr
source_metadata:
  volumes:
    ee4cdf3775a54a2db2422b48ca59df4e:
      base_file: v003.txt
      image_group_id: I1PD95848
      title: རྒྱུད་ཀྱི་རྒྱལ་པོ་ཆེན་པོ་དཔལ་དགྱེས་པའི་རྡོ་རྗེའི་དཀའ་འགྲེལ་སྤྱན་འབྱེད།
      total_pages: 1687
      volume_number: 3
